"""Cria tabelas iniciais

Revision ID: c3adc371964b
Revises: 'None'
Create Date: 2025-11-01 20:32:27.630060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3adc371964b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_fiscais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_prestador', sa.String(length=255), nullable=True),
    sa.Column('cnpj_prestador', sa.String(length=20), nullable=True),
    sa.Column('valor_total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('codigo_servico', sa.String(length=20), nullable=True),
    sa.Column('cnae', sa.String(length=20), nullable=True),
    sa.Column('tem_retencao_impostos', sa.Boolean(), nullable=True),
    sa.Column('detalhes_retencao', sa.String(length=500), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.Column('status_processamento', sa.Enum('PENDENTE', 'PROCESSADO', 'ERRO', name='statusprocessamento'), nullable=True),
    sa.Column('texto_extraido_raw', sa.Text(), nullable=True),
    sa.Column('data_upload', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_processamento', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_fiscais_cnpj_prestador'), 'notas_fiscais', ['cnpj_prestador'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notas_fiscais_cnpj_prestador'), table_name='notas_fiscais')
    op.drop_table('notas_fiscais')
    # ### end Alembic commands ###